const CONSTANTS = {};

CONSTANTS.ERROR_MESSAGE = {};

CONSTANTS.ERROR_MESSAGE.GRID_GET = "Request to get grid text failed:";

CONSTANTS.ENDPOINT = {};

CONSTANTS.ENDPOINT.GRID = "./api/grid";
CONSTANTS.ENDPOINT.PCA = "./data/pca.csv";
CONSTANTS.ENDPOINT.MDS = "./data/mds.csv";
CONSTANTS.ENDPOINT.TSNE = "./api/tsne.csv";

CONSTANTS.SIZE = {};
CONSTANTS.SIZE.MARGIN = { top: 30, right: 50, bottom: 30, left: 50 };
CONSTANTS.SIZE.WIDTH = 500 - CONSTANTS.SIZE.MARGIN.left - CONSTANTS.SIZE.MARGIN.right;
CONSTANTS.SIZE.HEIGHT = 300 - CONSTANTS.SIZE.MARGIN.top - CONSTANTS.SIZE.MARGIN.bottom;

export default CONSTANTS;
